spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/supportPortal
    password: 123456
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081

jwt:
  secret: '7iS0FcASEmnnlVvMrq0='
